### ISSUE TITLE
edgemesh to trimesh multimesh register

### ISSUE THREAD

**Issue by JcDai** [wildmeshing/wildmeshing-toolkit#434]

**Comment by daniel-zint** [comment]
Please provide a description of what needs to be done and link a pull request.

**Comment by zlyfunction** [comment]
Attempt to implement multi-mesh registration between edge mesh and triangle mesh, and test whether the map is valid and verify the consistency of the navigation.

**Comment by zlyfunction** [comment]
Attempt to implement multi-mesh registration between edge mesh and triangle mesh, and test whether the map is valid and verify the consistency of the navigation.

**Comment by zlyfunction** [comment]
It seems that the `register_child_mesh` function already in the `MultiMeshManager` is generic enough. The main remaining tasks are to implement some helper functions and conduct tests.
TODO:
- [ ] Mimic the `'test_register_child_mesh' `and `'test_multi_mesh_navigation' `test cases to test the behavior of `MultiMeshManager` between `EdgeMesh` and `TriMesh`.
- [ ] Complete `DEBUG_MultiMeshManager::check_child_map_valid` to support the map between `EdgeMesh` and `TriMesh`.
- [ ] Write a helper function to automatically register the boundary loop of a `TriMesh` as its child `EdgeMesh`.

**Comment by zlyfunction** [comment]
Updates:
1. add code updates from https://github.com/wildmeshing/wildmeshing-toolkit/pull/467 and https://github.com/wildmeshing/wildmeshing-toolkit/pull/469
2. in `map_tuple_between_meshes`, make sure that `source_mesh_base_tuple` and `source_mesh_target_tuple` has the same `global_cid`, in order to support mapping from higher dimensional mesh to a lower one
